name: BlueSkies
favicon: null
layout_spectrum: 0.5327756197657436
typography_spectrum: 0.27952
title: Explorations on Life!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020003'
    - '#287ab6'
    - '#bed5f3'
    - '#5c9dd3'
    - '#0b3273'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.7557592622470111
purpose: []
